name: AKBC
tagline: Automated Knowledge Base Construction
date: June 22-25 2020
proceedings_title: Proceedings of the Second AKBC Conference
analytics: UA-
logo:
  image: https://akbc.ws/2020/assets/img/logo_notext.png
  width: 50px
  height: auto
# uncomment the following line to show the site title next to the logo image
site_title: AKBC 2020
page_title:
  prefix: "AKBC 2020"
  separator: ": "
background_image: static/images/main.jpg
organization: AKBCOrganization Committee

# Remove or change to your chat server.
chat_server: 35.232.236.127:3000
default_presentation_id: 38922815
default_poster_pdf: /static/images/GLTR_poster.pdf

calendar:
  colors: #  Colors for the different event hashtags:
    ---: "#FFDAC1"
    poster: "#C7CEEA"
    talks: "#E2F0CB"
    invited: "#B5EAD7"
  sunday_saturday: false #  Include Sunday and Saturday

